### ISSUE TITLE
Fix super() call in D3Magics class

### ISSUE THREAD

**Issue by MattPitlyk** [ResidentMario/py_d3#1]
Line 19: The super call is missing arguments:

`super(D3Magics, self).__init__(**kwargs)`

It didn't run for me until I made that change, and now it works.

**Comment by ResidentMario** [comment]
That's because I neglected to test this in `2.7`, [Python version before 3.0 expected parent classes in the constructor](http://stackoverflow.com/questions/576169/understanding-python-super-with-init-methods). Should be fixed now.
