### ISSUE TITLE
Have a roadmap to port it to JupyterLab?

### ISSUE THREAD

**Issue by Honghe** [ResidentMario/py_d3#16]
It does not work in JupyterLab :D

**Comment by ResidentMario** [comment]
(missed this issue, apologies)

JupyterLab uses a very different system AFAIK. I'm not too familiar with the internals. I'm sure this is possible with JupyterLab too, but it's not really on my radar at the moment. Maybe eventually though...will leave this issue open for now.

**Comment by stefaneidelloth** [comment]
Here is a workaround for Jupyterlab:

```
%%html
<div id = "root"/>  
```
```

%%javascript
var d3Import = document.createElement('script')
d3Import.src = 'https://d3js.org/d3.v6.min.js';
d3Import.addEventListener('load', ()=>{
    d3.select('#root') 
      .html('Hello world from d3.js!');   
})
document.body.appendChild(d3Import);
```

![image](https://user-images.githubusercontent.com/12675339/97216123-a9d16280-17c5-11eb-8fc6-0a021840c3d3.png)

Or

![image](https://user-images.githubusercontent.com/12675339/97216559-527fc200-17c6-11eb-8ad4-5b8d5b4e04d1.png)

**Comment by krassowski** [comment]
Here is a solution which works in both classic Notebook and JupyterLab: https://discourse.jupyter.org/t/d3-in-jupyterlab/11367/4?u=krassowski

**Comment by ResidentMario** [comment]
[I have officially deprecated `py_d3`](https://github.com/ResidentMario/py_d3/commit/2e86ea8c4a281acb006cc76cfcf78bc7d8dab96f). It's had a long and, I hope, useful life, but I believe its time has ended. 🙂

For users that want an environment to interactively develop on D3.JS visualizations, I recommend Observable Notebooks. For users that want to do this stuff in Notebooks, [please see this Gist](https://gist.github.com/gnestor/f1893e0226ced227e910f11b769adc06). The link from @krassowski also looks good.
