### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by wangqianwen0418** [ResidentMario/py_d3#19]
I just copied the example in https://github.com/ResidentMario/py_d3/blob/master/notebooks/%25%25d3-4.0-example.ipynb,
but got the following erro:
![image](https://user-images.githubusercontent.com/19774198/50834654-9efad300-138f-11e9-94b1-76c199238b11.png)

**Comment by ResidentMario** [comment]
Did you `%load_ext py_d3` as well?

**Comment by wangqianwen0418** [comment]
> Did you `%load_ext py_d3` as well?

yes, just copy the example

**Comment by ResidentMario** [comment]
I updated the instruction in the notebook to use `%load_ext py_d3`. Assuming you do that, it works.
