### ISSUE TITLE
Unable to run specific version of D3

### ISSUE THREAD

**Issue by sl2902** [ResidentMario/py_d3#20]
I tried to run the py_d3 library on Kaggle kernel, but it failed
Here are the steps I followed

!pip install py_d3
%load_ext py_d3

%%d3
"3.5.17"

However, when I check the version, it points to 5.12.0. This results in the notebook failing to  produce any output. I get a d3.scale.category20() undefined error; this is because in the latest version it is d3.schemaCategory20. Interestingly, when I run this locally, on my machine, it runs fine, and the output is rendered. Any idea why it fails on Kaggle?

Any help is appreciated. Thanks!

**Comment by ResidentMario** [comment]
py_d3 requires that certain UI elements be present on the screen to work.
These UI elements are present in a notebook instance, but likely absent in
the (completely homebrew) Kaggle UI.

As a result py_d3 is not expected to work in Kaggle Notebooks, and I don't
claim to support them.
