### ISSUE TITLE
`d3.selectAll` not restricted to current cell

### ISSUE THREAD

**Issue by JobJob** [ResidentMario/py_d3#7]
Hi,

Just wanted to say thanks for this package and let you know that I made a minimal port of some of this project to Julia here: https://github.com/JobJob/D3Magic.jl

One other thing, when I was looking at the code it seemed [your regex](https://github.com/ResidentMario/py_d3/blob/master/py_d3/py_d3.py#L78) won't match "d3.selectAll(..." - or maybe I just missed something.

Cheers

**Comment by ResidentMario** [comment]
That's great to see!

A quick check on RegExr shows that you seem to be right about that. It's been a while since I wrote this but I'm pretty sure it works with `selectAll`, right? Would be a pretty serious bug if not. If you could check on that, that would be helpful.

**Comment by JobJob** [comment]
Yep, seems to be a problem. Try this one on a saved, or probably better, new notebook
```
%%d3

<script>
d3.selectAll("div").remove()
</script>
```

**Comment by ResidentMario** [comment]
Your patch with the fix is now live in `0.2.7`. Sorry it took so long; I totally forgot about this, and only caught it when I was doing a once over on things yesterday.

**Comment by JobJob** [comment]
Ha - no probs - I also forgot about it.
